// Code generated by sqlc. DO NOT EDIT.

package repo

import (
	"database/sql"
	"time"
)

type Gender struct {
	ID    int16  `json:"id"`
	Title string `json:"title"`
}

type User struct {
	ID             int64          `json:"id"`
	Email          string         `json:"email"`
	HashedPassword string         `json:"hashedPassword"`
	FirstName      string         `json:"firstName"`
	LastName       string         `json:"lastName"`
	BirthDay       sql.NullTime   `json:"birthDay"`
	Gender         int16          `json:"gender"`
	PhoneNumber    sql.NullString `json:"phoneNumber"`
	UpdatedAt      sql.NullTime   `json:"updatedAt"`
	DeletedAt      sql.NullTime   `json:"deletedAt"`
	CreatedAt      time.Time      `json:"createdAt"`
}
