// Code generated by mockery v2.5.1. DO NOT EDIT.

package mocks

import (
	context "context"
	repo "user/pkg/repo"

	mock "github.com/stretchr/testify/mock"
)

// Querier is an autogenerated mock type for the Querier type
type Querier struct {
	mock.Mock
}

// CreateGender provides a mock function with given fields: ctx, title
func (_m *Querier) CreateGender(ctx context.Context, title string) (repo.Gender, error) {
	ret := _m.Called(ctx, title)

	var r0 repo.Gender
	if rf, ok := ret.Get(0).(func(context.Context, string) repo.Gender); ok {
		r0 = rf(ctx, title)
	} else {
		r0 = ret.Get(0).(repo.Gender)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, title)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateUser provides a mock function with given fields: ctx, arg
func (_m *Querier) CreateUser(ctx context.Context, arg repo.CreateUserParams) (repo.User, error) {
	ret := _m.Called(ctx, arg)

	var r0 repo.User
	if rf, ok := ret.Get(0).(func(context.Context, repo.CreateUserParams) repo.User); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(repo.User)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, repo.CreateUserParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteGender provides a mock function with given fields: ctx, id
func (_m *Querier) DeleteGender(ctx context.Context, id int16) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int16) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteUserPermanent provides a mock function with given fields: ctx, id
func (_m *Querier) DeleteUserPermanent(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteUserSoft provides a mock function with given fields: ctx, id
func (_m *Querier) DeleteUserSoft(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetGender provides a mock function with given fields: ctx, id
func (_m *Querier) GetGender(ctx context.Context, id int16) (repo.Gender, error) {
	ret := _m.Called(ctx, id)

	var r0 repo.Gender
	if rf, ok := ret.Get(0).(func(context.Context, int16) repo.Gender); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(repo.Gender)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int16) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetHashedPassword provides a mock function with given fields: ctx, id
func (_m *Querier) GetHashedPassword(ctx context.Context, id int64) (string, error) {
	ret := _m.Called(ctx, id)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, int64) string); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserByEmail provides a mock function with given fields: ctx, email
func (_m *Querier) GetUserByEmail(ctx context.Context, email string) (repo.User, error) {
	ret := _m.Called(ctx, email)

	var r0 repo.User
	if rf, ok := ret.Get(0).(func(context.Context, string) repo.User); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Get(0).(repo.User)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserByID provides a mock function with given fields: ctx, id
func (_m *Querier) GetUserByID(ctx context.Context, id int64) (repo.User, error) {
	ret := _m.Called(ctx, id)

	var r0 repo.User
	if rf, ok := ret.Get(0).(func(context.Context, int64) repo.User); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(repo.User)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListGenders provides a mock function with given fields: ctx
func (_m *Querier) ListGenders(ctx context.Context) ([]repo.Gender, error) {
	ret := _m.Called(ctx)

	var r0 []repo.Gender
	if rf, ok := ret.Get(0).(func(context.Context) []repo.Gender); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repo.Gender)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RecoverDeletedUser provides a mock function with given fields: ctx, id
func (_m *Querier) RecoverDeletedUser(ctx context.Context, id int64) (repo.User, error) {
	ret := _m.Called(ctx, id)

	var r0 repo.User
	if rf, ok := ret.Get(0).(func(context.Context, int64) repo.User); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(repo.User)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateUserEmail provides a mock function with given fields: ctx, arg
func (_m *Querier) UpdateUserEmail(ctx context.Context, arg repo.UpdateUserEmailParams) (repo.User, error) {
	ret := _m.Called(ctx, arg)

	var r0 repo.User
	if rf, ok := ret.Get(0).(func(context.Context, repo.UpdateUserEmailParams) repo.User); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(repo.User)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, repo.UpdateUserEmailParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateUserInfo provides a mock function with given fields: ctx, arg
func (_m *Querier) UpdateUserInfo(ctx context.Context, arg repo.UpdateUserInfoParams) (repo.User, error) {
	ret := _m.Called(ctx, arg)

	var r0 repo.User
	if rf, ok := ret.Get(0).(func(context.Context, repo.UpdateUserInfoParams) repo.User); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(repo.User)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, repo.UpdateUserInfoParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateUserPassword provides a mock function with given fields: ctx, arg
func (_m *Querier) UpdateUserPassword(ctx context.Context, arg repo.UpdateUserPasswordParams) (repo.User, error) {
	ret := _m.Called(ctx, arg)

	var r0 repo.User
	if rf, ok := ret.Get(0).(func(context.Context, repo.UpdateUserPasswordParams) repo.User); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(repo.User)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, repo.UpdateUserPasswordParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateUserPhoneNumber provides a mock function with given fields: ctx, arg
func (_m *Querier) UpdateUserPhoneNumber(ctx context.Context, arg repo.UpdateUserPhoneNumberParams) (repo.User, error) {
	ret := _m.Called(ctx, arg)

	var r0 repo.User
	if rf, ok := ret.Get(0).(func(context.Context, repo.UpdateUserPhoneNumberParams) repo.User); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(repo.User)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, repo.UpdateUserPhoneNumberParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
