// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package http

import (
	http "github.com/go-kit/kit/transport/http"
	mux "github.com/gorilla/mux"
	http1 "net/http"
	endpoint "user/pkg/endpoint"
)

// NewHTTPHandler returns a handler that makes a set of endpoints available on
// predefined paths.
func NewHTTPHandler(endpoints endpoint.Endpoints, options map[string][]http.ServerOption) http1.Handler {
	m := mux.NewRouter()
	makeAddGenderHandler(m, endpoints, options["AddGender"])
	makeGetGenderHandler(m, endpoints, options["GetGender"])
	makeListGendersHandler(m, endpoints, options["ListGenders"])
	makeRemoveGenderHandler(m, endpoints, options["RemoveGender"])
	makeCreateUserHandler(m, endpoints, options["CreateUser"])
	makeGetUserByIDHandler(m, endpoints, options["GetUserByID"])
	makeGetUserByEmailHandler(m, endpoints, options["GetUserByEmail"])
	makeUpdateUserEmailHandler(m, endpoints, options["UpdateUserEmail"])
	makeUpdateUserPasswordHandler(m, endpoints, options["UpdateUserPassword"])
	makeUpdateUserInfoHandler(m, endpoints, options["UpdateUserInfo"])
	makeDeleteUserSoftHandler(m, endpoints, options["DeleteUserSoft"])
	makeRecoverUserHandler(m, endpoints, options["RecoverUser"])
	makeDeleteUserPermanentHandler(m, endpoints, options["DeleteUserPermanent"])
	makeVerifyPasswordHandler(m, endpoints, options["VerifyPassword"])
	return m
}
