// Code generated by sqlc. DO NOT EDIT.

package repo

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type User struct {
	ID             uuid.UUID      `json:"id"`
	Email          string         `json:"email"`
	PhoneNumber    sql.NullString `json:"phoneNumber"`
	HashedPassword string         `json:"hashedPassword"`
	FirstName      string         `json:"firstName"`
	LastName       string         `json:"lastName"`
	Gender         int16          `json:"gender"`
	BirthDay       sql.NullTime   `json:"birthDay"`
	UpdatedAt      sql.NullTime   `json:"updatedAt"`
	CreatedAt      time.Time      `json:"createdAt"`
}
